version: "3.9"

services:
  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9047"]
      interval: 10s
      retries: 10

  pat-fetcher:
    image: python:3.11-slim
    depends_on:
      dremio:
        condition: service_healthy
    environment:
      DREMIO_HOST: http://dremio:9047
      DREMIO_USERNAME: dremio
      DREMIO_PASSWORD: dremio1995
    volumes:
      - ./get_pat.py:/app/get_pat.py
    working_dir: /app
    command: /bin/sh -c "pip install requests && python get_pat.py"

  mcp-client:
    image: alexmerced/demo_dremio_mcp:version-00-01
    ports:
      - "5000:5000"
    depends_on:
      - dremio
    volumes:
      - ./mcp_servers.json:/app/mcp_servers.json
    environment:
      # Dremio Config
      DREMIO_URI: http://dremio:9047
      DREMIO_PAT: ...

      # LLM Config
      LLM_MODEL: openai:gpt-4.1
      DETAILED_OUTPUT: "false"

      # API Keys
      OPENAI_API_KEY: ...
      ANTHROPIC_API_KEY: ...
      GOOGLE_API_KEY: ...
      MISTRAL_API_KEY: ...
      COHERE_API_KEY: ...
      TOGETHER_API_KEY: ...
      FIREWORKS_API_KEY: ...
      AZURE_OPENAI_API_KEY: ...
      AZURE_OPENAI_ENDPOINT: ...
      AWS_ACCESS_KEY_ID: ...
      AWS_SECRET_ACCESS_KEY: ...
      AWS_REGION: us-east-1
